#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
    /run/ddclient-cache \
    /run/ddclient

# copy default config if not present in /config
if [[ ! -e /config/ddclient.conf ]]; then
    echo "DOMAIN=$DOMAIN TOKEN_SECRET=$TOKEN_SECRET"
    if [[ -z "$DOMAIN" || -z "$TOKEN_SECRET" ]]; then
      echo "Writing DEFAULT conf"
      cp /defaults/ddclient.conf /config
    else
      echo "Writing custom conf:"
      cat /defaults/ddclient-desec.conf | sed "s/[domain]/$DOMAIN/g" | sed "s/[token secret]/$TOKEN_SECRET/g" > /config/ddclient.conf
      cat /config/ddclient.conf
    fi
fi

# permissions
lsiown -R abc:abc \
    /config \
    /run/ddclient \
    /run/ddclient-cache

chmod 700 \
    /config \
    /run/ddclient-cache

chmod 600 \
    /config/*
