#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p \
    /run/ddclient-cache \
    /run/ddclient

# copy default config if not present in /config
if [[ ! -e /config/ddclient.conf ]]; then
    if [ -n "$DOMAIN" && -n "$TOKEN_SECRET" ]; then
      cat /defaults/ddclient-desec.conf | sed "s/[domain]/$DOMAIN/g" | sed "s/[token secret]/$TOKEN_SECRET/g" > /config/ddclient.conf
    else
      cp /defaults/ddclient.conf /config
    fi
fi

# permissions
lsiown -R abc:abc \
    /config \
    /run/ddclient \
    /run/ddclient-cache

chmod 700 \
    /config \
    /run/ddclient-cache

chmod 600 \
    /config/*
